### PR TITLE
chore: Fix tests by updating minitest version constraint

### PR DESCRIPTION
**Pull request by dazuma**
Attempt to fix the consistently failing tests (core, debugger, and logger).

* Change the minitest dependency to `~> 5.11.3` to avoid incompatibilities in the `5.12.x` series (and avoid the warnings printed by them).
* Add an apparently missing require in one of the core tests. Not sure why this started failing suddenly; might have been an upstream change we were depending on implicitly.

Note: I updated the minitest dependency only in those three libraries for now. This is just an attempt to get tests passing. It sounds like we still want to update it in the other libraries as well (which may involve synth work for generated gemspecs), as part of the work to address #4110.

### CODE REVIEW

**Comment by blowmage** [comment]
What do you think about capping Minitest in the Gemfile so the dependency doesn’t have to change?

**Comment by dazuma** [comment]
Hmm Logger still has some broken links in the generated docs. Investigating...

**Comment by dazuma** [comment]
@blowmage Yeah, that's a good idea. Means we wouldn't have to add a synth hack for generated gemspecs. I don't think any of the Gemfiles are generated.

**Comment by dazuma** [comment]
Yay tests pass now.

**Pull request merged**
