### PR TITLE
feat(spanner): add cmek db support

### PR DESCRIPTION
**Pull request by hengfengli**
This PR only includes the db support (for `create_database` and `get_database`) and I will create another PR for backup support. This way (smaller PR) would be easier for code review.

### CODE REVIEW

**Review by skuruppu — APPROVED** [review]

**Review by jiren — CHANGES_REQUESTED** [review]
@hengfengli Implementation looks good. 
Pending things are
 - doctest updates.
 - Acceptance tests.

To verify all things are ok run
`bundle exec rake ci`

**Comment by hengfengli** [comment]
> @hengfengli Implementation looks good.
> Pending things are
> 
> * doctest updates.
> * Acceptance tests.
> 
> To verify all things are ok run
> `bundle exec rake ci`

I ran `bundle exec rake ci` locally and it passes. 

* doctest updates: where should I update? I think the doctest passes. 
* Acceptance tests: we are planning to add this test into code samples.

**Comment by jiren** [comment]
@hengfengli Doctests are in `support/doctest_helper.rb` 

Here is one of the test which is failing on my machine.
https://github.com/googleapis/google-cloud-ruby/blob/f2022ed8e3fd4caf78fe0b56ed719568bdac2bc3/google-cloud-spanner/support/doctest_helper.rb#L125

**Comment by jiren** [comment]
@skuruppu Created PR https://github.com/googleapis/google-cloud-ruby/pull/8167 with doctest updates and example.

**Comment by skuruppu** [comment]
Closing since @jiren will rebase his PR.

**Pull request closed without merging**
