### PR TITLE
Fix coverage tasks

### LINKED ISSUE #4167: rake test:coverage reports 0.0% coverage at the gem level
Running `rake test:coverage` at the gem level generates reports with "0.0%" coverage. (I tested in bigquery and bigtable). The top-level `rake test:coverage` task appears to work correctly.

@blowmage commented:

> it looks like things have changed over time. originally the test task was defined like this:
```rb
task :test do
  $LOAD_PATH.unshift "lib", "test"
  Dir.glob("test/**/*_test.rb")
    .each { |file| require_relative file }
end
```

> but now the test task is defined like this:

```rb
Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = false
end
```

> that change is the reason why the coverage report generates with no coverage

### PR DESCRIPTION
**Pull request by blowmage**
The coverage tasks were not reporting correctly due to some changes in how the test task is being defined.
The require of the SimpleCov library now has to be declared in the test files, before Minitest is required.
The coverage configuration is moved to a .simplecov file.
The SimpleCov dependency has been updated.
The top-level coverage task's configuration of files to ignore in the report has been simplified and updated.

[fixes #4167]

### CODE REVIEW

**Comment by blowmage** [comment]
Coverage can be generated for all libraries by running `rake test:coverage` and `rake acceptance:coverage` from the top-level directory.

You can also generate all coverage reports for each gem individually by adding the following to the top-level `Rakefile` and running `rake test:coverage:each` and `rake acceptance:coverage:each`:

```ruby
namespace :test do
  namespace :coverage do
    desc "Runs tests with coverage for all gems individually."
    task :each, :bundleupdate do |t, args|
      bundleupdate = args[:bundleupdate]
      Rake::Task["bundleupdate"].invoke if bundleupdate
      valid_gems.each do |gem|
        Dir.chdir gem do
          Bundler.with_clean_env do
            header "RUNNING TESTS FOR #{gem}"
            run_task_if_exists "test:coverage"
          end
        end
      end
    end
  end
end

namespace :acceptance do
  namespace :coverage do
    desc "Runs acceptance tests with coverage for all gems individually."
    task :each, :bundleupdate do |t, args|
      bundleupdate = args[:bundleupdate]
      Rake::Task["bundleupdate"].invoke if bundleupdate
      valid_gems.each do |gem|
        Dir.chdir gem do
          Bundler.with_clean_env do
            header "RUNNING ACCEPTANCE TESTS FOR #{gem}"
            run_task_if_exists "acceptance:coverage"
          end
        end
      end
    end
  end
end
```

**Comment by quartzmo** [comment]
I'm trying this branch locally.

**Comment by blowmage** [comment]
I'm thinking synthtool will overwrite many of these changes, so i'll update the synth.py files for this change before merging.

**Comment by dazuma** [comment]
This is long out of date, and we're no longer going to be reporting coverage anyway, so I'm going to close this.

**Pull request closed without merging**
