### PR TITLE
fix(spanner) : add service address and port for operation client

### PR DESCRIPTION
**Pull request by jiren**
Issue #4422

### CODE REVIEW

**Comment by blowmage** [comment]
Can you also run `synthtool` so we can see what this change produces?

**Comment by jiren** [comment]
> Can you also run `synthtool` so we can see what this change produces?

Added generated code.

**Comment by quartzmo** [comment]
@blowmage This has been updated, PTAL.

**Comment by blowmage** [comment]
@dazuma Is this something that should be generalized everywhere?

**Comment by blowmage** [comment]
NM, it looks like it is everywhere but these two instances.

**Pull request merged**
