### PR TITLE
Update Authentication Guide

### LINKED ISSUE #4188: Authentication.MD references non existing method
#### Environment details

  - OS: macOS 10.15
  - Ruby version: 2.6.3
  - Gem name and version: google-cloud-dialogflow 0.7.0

#### Steps to reproduce

  1. Initialize a client with the code provided in AUTHENTICATION.MD: `client = Google::Cloud::Dialogflow.new`

#### Full backtrace

```ruby
NoMethodError (undefined method `new' for Google::Cloud::Dialogflow:Module)
	from (irb):7
```

#### Notes

This method doesn't seem to exist in the source code. I can get a new Agent by calling the `Agents.new` method in the `Dialogflow` module. Perhaps this is what was meant?

### PR DESCRIPTION
**Pull request by blowmage**
* Fix authentication guide code examples to use a correct
  client factory. (This library has several client factories).

This PR makes changes to the authentication guide for gems that have multiple clients per versioned package.

[fixes #4188]

### CODE REVIEW

**Comment by blowmage** [comment]
Dunno. @dazuma?

**Comment by dazuma** [comment]
Yeah they do, currently. `AUTHENTICATION.md` is being generated by a template in synthtool (https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/ruby_library/AUTHENTICATION.md). I don't know of a straightforward way to update the template to generate changes like these.

TBH the fact that this file is generated has caused other issues as well (e.g. #3494). I think we should probably just disconnect it from synthtool so we can edit the AUTHENTICATION.md files manually. (You can do that by removing the "common templates" section from the synth.py files.)

**Comment by blowmage** [comment]
Do you want detaching the auth guide from synthtool to be part of this pr? Or is that a separate change?

**Comment by dazuma** [comment]
Detaching the auth guide from synthtool just has to be done either before or at the same time as this PR (otherwise the next synth will just revert these changes). I don't really care whether we add it to this PR or create a new one.

**Comment by TheRoyalTnetennba** [comment]
I believe we added the .repo-metadata fields   "module_name",  "module_name_credentials", and "env_var_prefix": "AUTOML" just for this. We could change "module_name_credentials" to something like "client_factory" and update https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/ruby_library/AUTHENTICATION.md

**Comment by blowmage** [comment]
I'm gonna place these rules in the synth.py files for the guides that have changed, and then open a separate issue to remove the auth guide from all the synth.py files.

**Pull request merged**
