### PR TITLE
Move translate gem to GAPIC

### PR DESCRIPTION
**Pull request by blowmage**
BREAKING CHANGE: This replaces the previous hand-written gem.

### CODE REVIEW

**Comment by blowmage** [comment]
I don't suppose there is any reason to also include v3beta1, is there?

**Comment by dazuma** [comment]
Here's the decision we came up with after a discussion with product:

V2 and V3 will be treated as they should be: as current and legacy (rather than being branded as basic/advanced). The only requirement is that we need to support both. So what we need to do is move the current V2 veneer into a `V2::` namespace (i.e. as a peer of the V3 gapic) and then generate V3 in its normal location. So it should appear that the two version clients are both present as if we're generating both, but V2 happens to be handwritten.

We can optionally add a toplevel factory method that takes a `:version` parameter, as we do with our other gapic clients. This is a nice-to-have but not required, and it may be tricky since the V2 veneer's constructor arguments may be substantially different from the V3 gapic's constructor arguments.

Then we release it as a semver-major.

**Comment by dazuma** [comment]
And no, don't include v3beta1.

**Comment by blowmage** [comment]
Closing in favor of #4258

**Pull request closed without merging**
