### PR TITLE
fix: Removing samples that are in ruby-docs-samples

### PR DESCRIPTION
**Pull request by billyjacobson**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/google-cloud-ruby/issues) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea.
- [ ] Follow the instructions in [CONTRIBUTING](CONTRIBUTING.md). Most importantly, ensure the tests and linter pass by running `bundle exec rake ci` in the gem subdirectory.
- [ ] Update code documentation if necessary.

closes: #<issue_number_goes_here>

### CODE REVIEW

**Comment by tmatsuo** [comment]
@billyjacobson 

It seems like the devsite is still using `bigtable_quickstart` in this repo.
Can you do the following?

1. Update devsite source for (this page)[https://cloud.google.com/bigtable/docs/reference/libraries#client-libraries-install-ruby] to use `bigtable_quickstart` in ruby-docs-samples and publish the page.
2. Try updating the snippet-bot comment by checking `Refresh this comment` checkbox (it might take some time for data propagation before snippet-bot stops complaining).
3. Once there's no violations, merge the PR.

**Comment by billyjacobson** [comment]
> @billyjacobson
> 
> It seems like the devsite is still using `bigtable_quickstart` in this repo.
> Can you do the following?
> 
> 1. Update devsite source for [this page](https://cloud.google.com/bigtable/docs/reference/libraries#client-libraries-install-ruby) to use `bigtable_quickstart` in ruby-docs-samples and publish the page.
> 2. Try updating the snippet-bot comment by checking `Refresh this comment` checkbox (it might take some time for data propagation before snippet-bot stops complaining).
> 3. Once there's no violations (and of course the reviewers are happy), merge the PR.

Hey I made the changes to devsite several days ago and clicked refresh, but it isn't updating.

**Comment by quartzmo** [comment]
I'm wondering if it is worth the trouble to update the devsite source to point `bigtable_quickstart ` to ruby-docs-samples, given that our goal is to move the samples *back* to this location in google-cloud-ruby. My PR GoogleCloudPlatform/ruby-docs-samples#581 removes the obstacle to doing this by converting the samples' testing to Minitest.

**Comment by billyjacobson** [comment]
> I'm wondering if it is worth the trouble to update the devsite source to point `bigtable_quickstart ` to ruby-docs-samples, given that our goal is to move the samples _back_ to this location in google-cloud-ruby. My PR [GoogleCloudPlatform/ruby-docs-samples#581](https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/581) removes the obstacle to doing this by converting the samples' testing to Minitest.

I've already submitted the PR, so not much trouble really. We just can't have this code in both places since it messes up the devrel samples tracker

**Comment by quartzmo** [comment]
With PR GoogleCloudPlatform/ruby-docs-samples#581 now merged, I am ready to move the samples in ruby-docs-samples back to the locations being deleted in this PR.

**Comment by billyjacobson** [comment]
Okay cool that works for me then! Sorry for the conflicting code for this, hard to stay organized across all the repos. I can close this PR if that is the easiest way to proceed.

**Comment by quartzmo** [comment]
@TheRoyalTnetennba Do you see anything blocking us from closing this PR, and replacing the contents of [google-cloud-ruby/google-cloud-bigtable/samples](https://github.com/googleapis/google-cloud-ruby/tree/master/google-cloud-bigtable/samples) with (more or less) the contents of [ruby-docs-samples/bigtable](https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/master/bigtable)? Once that's done, will you be able to change all the docs links to point to `google-cloud-ruby/google-cloud-bigtable/samples`?

**Comment by quartzmo** [comment]
I got a thumbs up offline from @TheRoyalTnetennba for the move from ruby-docs-samples/bigtable to google-cloud-ruby/google-cloud-bigtable/samples, so I'll do that soon.

**Pull request closed without merging**
