### PR TITLE
Update storage class examples in docs and tests

### LINKED ISSUE #4006: Update MultiRegional and Regional to Standard
(I don't have assign privileges in this repository but this should be assigned to @quartzmo )

Previously, we implemented the concept of "Location Type" to move the concept of bucket location away from storage class. It is no longer considered correct to use "MultiRegional" or "Regional" as a storage class, instead those should be location types.

As such, we need to update every instance of the "MultiRegional" and "Regional" storage in samples, library documentation, and tests to use "Standard" instead--Standard is a correct storage class.

Note that "MultiRegional" and "Regional" should only be replaced with "Standard" in cases where they are used a storage class. If they're used as a location type, that's fine and doesn't need to be replaced.

https://github.com/googleapis/google-cloud-ruby/blob/e55655699b66b765b49f4f40d6ecc7f2ab0d4c07/google-cloud-storage/lib/google/cloud/storage/bucket/lifecycle.rb#L55
https://github.com/googleapis/google-cloud-ruby/blob/01b8f514813cac2fd784a840010306d96607f797/google-cloud-storage/test/google/cloud/storage/bucket_update_test.rb
https://github.com/googleapis/google-cloud-ruby/blob/e55655699b66b765b49f4f40d6ecc7f2ab0d4c07/google-cloud-storage/test/google/cloud/storage/lazy/bucket_update_test.rb
https://github.com/googleapis/google-cloud-ruby/blob/01b8f514813cac2fd784a840010306d96607f797/google-cloud-storage/acceptance/storage/bucket_test.rb
https://github.com/googleapis/google-cloud-ruby/blob/6a889c312037ebcabe5555bac6a7288e718b944a/google-cloud-storage/support/doctest_helper.rb#L1182
https://github.com/googleapis/google-cloud-ruby/blob/01b8f514813cac2fd784a840010306d96607f797/google-cloud-storage/lib/google/cloud/storage/bucket.rb#L237

### PR DESCRIPTION
**Pull request by quartzmo**
Replace `MULTI_REGIONAL` and `REGIONAL` with `STANDARD` and `NEARLINE` in code examples and tests.

[closes #4006]

### CODE REVIEW

**Comment by quartzmo** [comment]
@JesseLovelace This PR is ready, PTAL, thanks!

**Comment by quartzmo** [comment]
@JesseLovelace Is anything blocking merging and releasing this PR?

**Comment by JesseLovelace** [comment]
Nothing other than the fact that I don't have permission to do so in this repo :)

**Comment by quartzmo** [comment]
OK, we’ll do it soon!

**Comment by quartzmo** [comment]
Released in 1.21.1 / 2019-09-30 (PR #4069)

**Pull request merged**
