### PR TITLE
chore: Remove hacks in place for old versions of Ruby

### PR DESCRIPTION
**Pull request by dazuma**
What's missing? Feel free to add to this PR!

### CODE REVIEW

**Comment by blowmage** [comment]
This looks like it could be removed:

https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-debugger/lib/google/cloud/debugger/breakpoint/evaluator.rb#L127

**Comment by dazuma** [comment]
Thanks @blowmage! I removed those, as well as some skipped tests in debugger.

**Comment by blowmage** [comment]
[Oops](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-core/test/google/cloud/errors/error_cause_test.rb#L49-L50)

```
  1) Failure:
Google::Cloud::Error::cause#test_0001_always has a cause [/tmpfs/src/github/google-cloud-ruby/google-cloud-core/test/google/cloud/errors/error_cause_test.rb:49]:
Expected nil to be a kind of StandardError, not NilClass.
```

**Comment by dazuma** [comment]
Hmm maybe we can remove the "unsupported ruby" warnings in `google-cloud-core/lib/google/cloud.rb`.

**Comment by blowmage** [comment]
I think that makes sense.

**Comment by dazuma** [comment]
Removed Ruby version warnings. The methods were always marked as `@private` so should be okay to delete them.

**Pull request merged**
