### PR TITLE
chore (translate): removed unsupported samples

### PR DESCRIPTION
**Pull request by munkhuushmgl**
Devsite update: cl/364663635

go/cloud-ai-2021-snippet-cleanup

### CODE REVIEW

**Review by dazuma — APPROVED** [review]
chore(translate): Remove unsupported samples

**Comment by dazuma** [comment]
Before merging this, I'd like to rescue one test of the V3 service to use as an acceptance test.

**Comment by munkhuushmgl** [comment]
> Before merging this, I'd like to rescue one test of the V3 service to use as an acceptance test.

Let me know how I can help

**Comment by dazuma** [comment]
@munkhuushmgl Smoke test PR: #11228

**Pull request merged**
