### PR TITLE
doc(spanner): document single use as default

### PR DESCRIPTION
**Pull request by olavloite**
Document that Cloud Spanner will use a single use read-only transaction as default for queries when no other option is specified. Also changes the example code for the database client to show how to execute a single query using a single use read-only transaction, instead of a read/write transaction.

### CODE REVIEW

**Comment by olavloite** [comment]
cc @hengfengli @jiren

**Review by hengfengli — APPROVED** [review]
LGTM.

**Comment by hengfengli** [comment]
@olavloite Same here. Please rebase it. Thanks.

**Comment by olavloite** [comment]
> @olavloite Same here. Please rebase it. Thanks.

done

**Pull request merged**
