### PR TITLE
Added `File.open` to quickstart example

### PR DESCRIPTION
**Pull request by 256hz**
Currently, the `response` object in the example is only stored in memory. It's not self-evident that the `response`'s `audio_content` method is the way to work with the audio.  Since the example is encoded as an MP3, I think it's natural to show the first-time user how to save that file to disk, and thus introduce them to that method.

### CODE REVIEW

**Comment by quartzmo** [comment]
@256hz This PR is a little tricky because the contents of this package are generated, and manual changes will be overwritten.

@dazuma This PR manually restores a final line in the code example that was originally in the README, but which disappeared when the example was updated in commit fe8fac3. I agree with @256hz that it is useful to show new users how to consume the response, since `response.audio_content` is binary data. Do you think we could suggest to the API owner to re-add the line, or else perhaps re-add it with synth.py?

**Comment by quartzmo** [comment]
@dazuma Is it worth the effort/mess in synth.py to try to accommodate this suggested change?

**Comment by dazuma** [comment]
I'm okay throwing in a synth hack for now. We have a sample autogen project in progress that should let us improve these generated samples in the long run.

**Comment by quartzmo** [comment]
@256hz I'm going to close this PR now, since it doesn't work to directly change this file in a generated library. I'll try to open a PR soon that will make the change in `synth.py`. Thanks!

**Comment by 256hz** [comment]
@quartzmo Sounds good.  Thanks for your responsiveness on this!

**Pull request closed without merging**
