### PR TITLE
Add Speech generated samples

### PR DESCRIPTION
**Pull request by beccasaurus**
Please add labels:
 - `do not merge`
 - `api: speech`

----

**This PR is a companion to a similar PR sent for PHP:** https://github.com/googleapis/google-cloud-php/pull/1991

I send this **Ruby PR** to show differences between the generated **PHP** + **Ruby** sample artifacts.

_I also sent a similar PR to **Python:**_ https://github.com/googleapis/google-cloud-python/pull/8210

=> @dwsupplee
/cc @TheRoyalTnetennba @dazuma 
/fyi @busunkim96 @googleapis/samplegen 

----

### The following is the body of the PHP Pull Request _(for context)_ –

Hello there, dear PHP friends! 🐘

We'd like to incorporate the samples which GAPIC generator now supports into `google-cloud-php`.

### tl;dr

These things are required to **"Make it go"**
 - PHP samples generated should be copied into `samples/` directory by synth.py (`gapic-generator`)
 - Tests for code samples should be copied into `samples/...` directory from googleapis (`synthtool`)
 - Code samples resources should be copied into `samples/...` directory from googleapis (`synthtool`)
 - PHP library CI should be setup to run code sample tests (`google-cloud-php`)
  ^ _**I need y'all's help with this last one!**_

More info: go/library-samples (internal)

### End Goal

🤖 **Autosynth sends PRs for new / modified code samples and tests**
 
_Should work once google-cloud-php is configured to run system tests for generated samples in CI_ ✨

### This PR

This PR serves the purpose of being an **_example Pull Request_** with _generated samples_ to **use for CI setup**.

> I've communicated with some of y'all who are expecting this PR for discussion and configuring CI

The actual diff of this PR is a result of doing the following:

 1. **Update `synth.py`** to generate samples _(currently opt-in feature behind a --dev_samples flag)_
 2. _Run [script][include_samples] with functionality I plan to get into SynthTool as include_samples=True (will send PR)_
 3. **Run synth.py** to generate the samples _(and supplemental [script][include_samples] to add tests + resources for samples)_
 
#### Companion PRs

To help with discussion / see differences between a couple languages, I send PRs to Python and Ruby:
 - https://github.com/googleapis/google-cloud-ruby/pull/3431
 - https://github.com/googleapis/google-cloud-python/pull/8210

#### If you want to reproduce this diff:

 1. Clone `google-cloud-php` and checkout fresh master and cd Speech/
 2. Edit `synth.py` to add samples `s.copy(library / 'samples/')`  
     _and enable sample generation `--dev_samples`_
 3. Run synth `python3 -m synthtool`
 4. _(Run polyfill script for missing functionality)_
    ```
    curl -LO https://gist.github.com/beccasaurus/8ac942988a8f6021a6bf938eb0b6858b/raw/include_samples.sh
    chmod +x include_samples.sh
    ./include_samples.sh speech "v1 v1p1beta1" php
    ```
 5. Look at the resulting samples/ directory

#### If you want to run the tests:

 1. Install the googleapis code sample test runner:
    ```
    python3 -m pip install sample-tester
    ```
 2. Run the tests
    ```
    sample-tester samples/*/test/*
    ```
    ```
    # just v1p1beta1 tests
    sample-tester samples/v1p1beta1/test/*

    # just a certain test
    sample-tester --cases "My test name" samples/v1/test/*

    # show the commands which invoke each sample with the resulting STDOUT
    sample-tester -v detailed samples/*/test/*

    https://sample-tester.readthedocs.io/
    ```
 
[include_samples]: https://gist.github.com/beccasaurus/8ac942988a8f6021a6bf938eb0b6858b

### CODE REVIEW

**Comment by quartzmo** [comment]
CI is [failing on Rubocop errors](https://source.cloud.google.com/results/invocations/c978a7c3-96cc-434c-b62f-24b4dd031fed/log) in the `samples` directory.

**Comment by TheRoyalTnetennba** [comment]
AFAICT gapic doesn't rely on `rubocop -a`

**Comment by hzyi-google** [comment]
Sooooo, looking at all the offenses detected:

These errors can and should be fixed in the generator (nice catch, good bot!):
1. Final newline missing
2. method def using parentheses
3. prefers `$PROGRAM_NAME` over `$0`
4. incorrect indentation for comments

These errors are hard to avoid in the generator, but can be easily fixed by a formatter:
5. line too long
6. extra blank lines in code
7. Use underscores(_) as thousands separator and separate every 3 digits with them

And some other errors are generally inevitable:
8 Assignment Branch Condition size for sample_long_running_recognize is too high.
9 Method has too many lines

IIUC, the report shows that RoboCop only considers the check failed when 5 happens (and only when the line has more than 95 characters it seems).

**Comment by TheRoyalTnetennba** [comment]
Do you want me to make a rubocop.yml for the samples, with exceptions added for ABC size and line lenght? We did something similar for https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/master/.rubocop.yml.

**Comment by beccasaurus** [comment]
@TheRoyalTnetennba I'd be down with this. We can keep 1 - 4, because those are good changes to make to the generator!

If the samples disable #4 (correct comment indentation), we should also have that – sometimes the `# [START` tags may not be indented at the code level a comment might normally be

```rb
def
# [START body
  # [START create_client
  client = make_me_a_delicious_client
  # [END create_client

  stuff!
# [END body
end
```

**Comment by beccasaurus** [comment]
🧹 Out-of-date / Deprecated

`301 Redirect =>` #3992

**Pull request closed without merging**
