### PR TITLE
fix(spanner): extract binary retry info from error

### LINKED ISSUE #11655: spanner: RetryInfo in AbortedError is not correctly decoded
The `RetryInfo` that is returned by Cloud Spanner when a transaction is aborted is not correctly decoded and parsed by the Ruby Spanner client. The `RetryInfo` is binary encoded in the metadata trailer `google.rpc.retryinfo-bin`, while the client tries to read an ASCII value from `retryDelay` which does not exist.

### PR DESCRIPTION
**Pull request by olavloite**
Retry info that is returned by Cloud Spanner is binary encoded in the metadata of an error. This was not correctly decoded by the Spanner client.

Fixes #11655

### CODE REVIEW

**Comment by hengfengli** [comment]
There is a lint error. I guess it prefers: 

```
retry_info = Google::Rpc::RetryInfo.decode err.metadata["google.rpc.retryinfo-bin"]
```

**Comment by hengfengli** [comment]
@JustinBeckwith Please help to merge this PR. Thanks.

**Comment by hengfengli** [comment]
@olavloite Can you please rebase with the main branch? There is a fix for the acceptance test. I tried to pull your PR to my local and merge the main branch to it, but my push gets rejected.

**Comment by olavloite** [comment]
> @olavloite Can you please rebase with the main branch? There is a fix for the acceptance test. I tried to pull your PR to my local and merge the main branch to it, but my push gets rejected.

Done.

**Pull request merged**
