### PR TITLE
Secret Manager resource path helpers

### PR DESCRIPTION
**Pull request by blowmage**
This PR adds the resource path helpers as defined in googleapis/gapic-generator-ruby#315.

/cc @sethvargo

### CODE REVIEW

**Comment by sethvargo** [comment]
Hey @blowmage - this looks great, but it seems to be missing `project_path(project:)` which would return `"projects/${project}"`

**Comment by blowmage** [comment]
@sethvargo I do see that a `cloudresourcemanager.googleapis.com/Project` resource type is [referenced in the protos](https://github.com/googleapis/googleapis/blob/master/google/cloud/secrets/v1beta1/service.proto#L215-L217), but the resource is not defined. We would need something like the following added to one of the proto files in order for that helper method to be generated:

```proto
option (google.api.resource_definition) = {
  type: "cloudresourcemanager.googleapis.com/Project"
  pattern: "projects/{project}"
};
```

**Comment by blowmage** [comment]
Looks like the rubocop checks are failing. I must have missed something when i generated these files. Once the open microgenerator PRs are merged I will regen these files and they should pass. Apologies for the noise.

**Comment by sethvargo** [comment]
Hey @blowmage hmm - that feels odd. All the other languages generated project_path helpers with the existing protos. I can check with the team, but why does Ruby have this additional requirement?

/cc @dazuma

**Comment by dazuma** [comment]
@sethvargo I'm unsure, unless there is special case logic in the other language generators treating the `project` resource as special.

It's also possible that this is a microgenerator vs legacy generator difference. Is there any difference between the behavior of one of the languages currently on the microgenerator (e.g. Node, C#) vs one of the languages not there yet (e.g. Python, Java)?

**Comment by blowmage** [comment]
This PR has been updated with all the resource changes that were made to the microgenerator.

**Comment by blowmage** [comment]
I checked and the resource in defined in the [`google/cloud/common_resources.proto`](https://github.com/googleapis/googleapis/blob/master/google/cloud/common_resources.proto#L26) file. If we add that proto to the list of protos used to define the secret manager gem then the `project_path` helper method should be generated.

**Comment by sethvargo** [comment]
@dazuma nope - node, python, dotnet, and java all have them. @blowmage is that in scope for this PR?

**Comment by blowmage** [comment]
> is that in scope for this PR?

@sethvargo Yes. I will change the definition for the gem to include the missing proto and regenerate. Will have an updated PR later tonight.

**Comment by blowmage** [comment]
I've updated the source protos to include the new file, and updated the generated files that include the `project_path` helper method.

**Comment by sethvargo** [comment]
@danzuma - can you ping me when you release a new version of the SM gem? It's not urgent as our samples are fine as-is, but I have a backlog item to update them to use the path helpers eventually.

**Comment by dazuma** [comment]
@sethvargo https://rubygems.org/gems/google-cloud-secret_manager/versions/0.2.0

**Pull request merged**
