### PR TITLE
feat: quota_project can be set via library configuration

### PR DESCRIPTION
**Pull request by dazuma**
ref: #6248

This PR handles all veneers that are backed by gapics.

### CODE REVIEW

**Review by quartzmo — COMMENTED** [review]
The only change I see in this PR is adding `quota_project` to `config`. Where is it read and passed to the generated clients?

**Comment by dazuma** [comment]
Generated gapics already define `quota_project` in their generated configs. The generated clients read the configs in their constructors, and this includes fallback code where if a field is not set in the generated config, it falls back to higher namespaces (which would include the veneer config). This was the compatibility mechanism we designed so older (veneer) configs will still work.

For example, the generated `Google::Cloud::Datastore::V1::Datastore::Client::Configuration` class already includes `quota_project`. The `Google::Cloud::Datastore::V1::Datastore::Client` constructor already reads the field. However, if `Google::Cloud::Datastore::V1::Datastore::Client::Configuration#quota_project` is not set, the generated client constructor falls back to looking up the namespaces for another configuration object. So if the veneer is present, it will find `Google::Cloud::Datastore.configure`, and use its `quota_project`.

**Review by quartzmo — APPROVED** [review]
@dazuma Thank you for the great explanation of how this works with the new generated clients!

**Comment by quartzmo** [comment]
@dazuma I can take care of it for all of them since I need to get it done before releasing #14405 and #14432.

**Pull request merged**
