### PR TITLE
add ".html" to urls ending in a capitalized word

### PR DESCRIPTION
**Pull request by TheRoyalTnetennba**

### CODE REVIEW

**Comment by quartzmo** [comment]
I think as this logic grows more complex it should be moved into the [jsondoc-forwarder](https://github.com/quartzmo/jsondoc-forwarder) where it can be [unit tested](https://github.com/quartzmo/jsondoc-forwarder/blob/master/test/test.js).

Should we move ownership of jsondoc-forwarder? If not to a standalone repo, maybe as a orphan branch of google-cloud-ruby?

**Comment by blowmage** [comment]
I don't think this logic belongs in jsondoc-forwarder. It is needed to fix the lack of content negotiation on the GCS site that we were depending on when jsondoc-forwarder was originally written. But, any gh-pages URL missing the extension needs to be fixed when redirecting to the GCS site. I think this change is mostly correct.

It would be good to have some test coverage though. I am not sure if/how anchors are propogated. e.g.

https://googleapis.github.io/google-cloud-ruby/docs/latest/Google/Cloud/PubSub#new-class_method
https://googleapis.github.io/google-cloud-ruby/docs/latest/#Publishing_Messages

**Comment by blowmage** [comment]
This doesn't take into account the anchor. I've pulled this locally, and as expected this URL:

http://127.0.0.1:4000/google-cloud-ruby/docs/google-cloud-asset/latest/file.AUTHENTICATION

Is properly redirected to:

https://googleapis.dev/ruby/google-cloud-asset/latest/file.AUTHENTICATION.html

However, this URL:

http://127.0.0.1:4000/google-cloud-ruby/docs/google-cloud-asset/latest/file.AUTHENTICATION.html#Creating_a_Service_Account

Is redirected to the wrong URL:

https://googleapis.dev/ruby/google-cloud-asset/latest/file.AUTHENTICATION#Creating_a_Service_Account.html

**Comment by blowmage** [comment]
Now the following URL:

http://127.0.0.1:4000/google-cloud-ruby/docs/google-cloud-asset/latest/file.AUTHENTICATION

Is being redirected to:

https://googleapis.dev/ruby/google-cloud/latest/file.AUTHENTICATION.html

But I was expecting it to redirect to:

https://googleapis.dev/ruby/google-cloud-asset/latest/file.AUTHENTICATION.html

**Comment by TheRoyalTnetennba** [comment]
(In my head at least) jsondoc-forwarder is a complete product - (i hope) we won't be adding new broken urls of the format that it fixes. It's easier to work on the new, similar but different functionality in a different project, so I know I won't be breaking anything jsondoc-forwarder is doing. I did separate out the new redirect logic and add unit tests.

**Comment by blowmage** [comment]
Pulling the latest code and all these redirects work fine:

http://127.0.0.1:4000/google-cloud-ruby/docs/google-cloud-asset/latest/file.AUTHENTICATION
->
https://googleapis.dev/ruby/google-cloud-asset/latest/file.AUTHENTICATION.html

http://127.0.0.1:4000/google-cloud-ruby/docs/google-cloud-asset/latest/file.AUTHENTICATION.html#Creating_a_Service_Account
->
https://googleapis.dev/ruby/google-cloud-asset/latest/file.AUTHENTICATION.html#Creating_a_Service_Account

http://127.0.0.1:4000/google-cloud-ruby/docs/google-cloud-asset/latest/Google/Cloud/Asset/V1/AssetServiceClient
->
https://googleapis.dev/ruby/google-cloud-asset/latest/Google/Cloud/Asset/V1/AssetServiceClient.html

http://127.0.0.1:4000/google-cloud-ruby/docs/google-cloud-asset/latest/Google/Cloud/Asset/V1/AssetServiceClient.html
->
https://googleapis.dev/ruby/google-cloud-asset/latest/Google/Cloud/Asset/V1/AssetServiceClient.html

However, this URL does not work:

http://127.0.0.1:4000/google-cloud-ruby/#/docs/google-cloud-pubsub/latest/google/cloud/pubsub

Instead, the page loads and there is the following error in the console:

```
ReferenceError: Can't find variable: DevsiteForwarder
/google-cloud-ruby/js/jsondoc-forwarder-init-0.1.0.js:998
```

**Pull request merged**
