### PR TITLE
Update pubsub synth file to ensure proto modules are created and to alias old module names

### PR DESCRIPTION
**Pull request by dazuma**
This deals with the issues found in #2782 . Specifically, it inserts the following code before the flattened module declarations:

```ruby
module Google
  module Cloud
    module PubSub
    end
  end
  Pubsub = Cloud::PubSub unless const_defined? :Pubsub
end
```

This ensures that:
1. The parent modules are created so that `module Google::Cloud::PubSub::V1` will work.
2. `Google::Pubsub` (the old namespace) is properly aliased to `Google::Cloud::PubSub` because the generated code still references the old namespace. We'll have to work separately to update the generated code.

### CODE REVIEW

**Comment by quartzmo** [comment]
With formatting, the replacement string appears to be:

```rb
module Google
  module Cloud
    module PubSub
    end
  end
  Pubsub = Cloud::PubSub unless const_defined? :Pubsub
end
module Google::Cloud::PubSub::V1
```

It appears to initialize `Google::Pubsub`?

**Comment by blowmage** [comment]
I believe we need both `Google::Pubsub` and `Google::Cloud::Pubsub` to point to `Google::Cloud::PubSub` to remain backwards compatible. Is that correct?

**Comment by jbolinger** [comment]
> (2) The gapic code is still generating in the old namespace (`Google::Cloud::Pubsub`). There probably is another configuration that needs to be tweaked to get it to generate in the new namespace. Until that happens, @blowmage I cannot define `Google::Cloud::Pubsub` as an alias.

@dazuma I think you're looking for this, which doesn't look like it's been updated: https://github.com/googleapis/googleapis/blob/0ac60e21a1aa86c07c1836865b35308ba8178b05/google/pubsub/v1/pubsub_gapic.yaml#L24

Rather annoying that we have so many places where this has to be configured.

**Comment by dazuma** [comment]
Superseded by #2840

**Pull request closed without merging**
