### PR TITLE
doc: add documentation for NUMERIC data type

### PR DESCRIPTION
**Pull request by olavloite**
Adds documentation for the NUMERIC data type and its default mapping.

### CODE REVIEW

**Review by hengfengli — APPROVED** [review]
LGTM. Thanks for fixing the docs.

**Comment by hengfengli** [comment]
Strange. The error says `Column boxes.id has type NUMERIC, but is part of the primary key.` and it's related to `google-cloud-spanner/acceptance/spanner/backup_operations_test.rb`. However, your changes do not touch this file at all. 😭

**Comment by hengfengli** [comment]
I found the reason: 

https://github.com/googleapis/google-cloud-ruby/blob/0b121e312b5d421e591de64beebe4fb04c170549/google-cloud-spanner/acceptance/spanner_helper.rb#L191-L196

@jiren Do we accept NUMERIC as a part of a primary key? See the Valid Key Column Type in [the official doc](https://cloud.google.com/spanner/docs/data-types#allowable_types).

**Comment by jiren** [comment]
> I found the reason:
> 
> https://github.com/googleapis/google-cloud-ruby/blob/0b121e312b5d421e591de64beebe4fb04c170549/google-cloud-spanner/acceptance/spanner_helper.rb#L191-L196
> 
> @jiren Do we accept NUMERIC as a part of a primary key? See `Valid Key Column Type` in [the official doc](https://cloud.google.com/spanner/docs/data-types#allowable_types).

@hengfengli  The current released Google Spanner Service is not supporting NUMERIC type as primary key.  It was added into stage env. I will create a PR to skip this test.

**Comment by hengfengli** [comment]
> > I found the reason:
> > https://github.com/googleapis/google-cloud-ruby/blob/0b121e312b5d421e591de64beebe4fb04c170549/google-cloud-spanner/acceptance/spanner_helper.rb#L191-L196
> > 
> > @jiren Do we accept NUMERIC as a part of a primary key? See `Valid Key Column Type` in [the official doc](https://cloud.google.com/spanner/docs/data-types#allowable_types).
> 
> @hengfengli The current released Google Spanner Service is not supporting NUMERIC type as primary key. It was added into stage env. I will create a PR to skip this test.

Thanks for that.

**Comment by hengfengli** [comment]
The acceptance test fails due to a weird reason. The error shows: 

```
  1) Google Cloud Spanner API samples write data with array types and read
     Failure/Error:
       write_read_bool_array project_id: @project_id,
                             instance_id: @instance.instance_id,
                             database_id: database.database_id

     ArgumentError:
       wrong number of arguments (given 1, expected 2)
     # ./spanner_samples.rb:1506:in `write_read_bool_array'
     # ./spec/spanner_samples_spec.rb:1459:in `block (3 levels) in <top (required)>'
     # ./spec/spanner_samples_spec.rb:128:in `capture'
     # ./spec/spanner_samples_spec.rb:1457:in `block (2 levels) in <top (required)>'
```

I reproduced the error locally but I tried to print out some debugging info: 

```ruby
  example "write data with array types and read" do
    puts "test begin - 1"
    database = create_boxes_database
    puts "test end - 1"

    capture do
      puts "test begin - 2"
      write_read_bool_array project_id: @project_id,
                            instance_id: @instance.instance_id,
                            database_id: database.database_id
      puts "test end - 2"
    end

    puts "test start - 3"
    expect(captured_output.split("\n")).to match_array(["true", "false", "true"])
    puts "test end - 3"

```

It only prints out and then fails: 

```
test begin - 1
test end - 1
```

**Comment by jiren** [comment]
> The acceptance test fails due to a weird reason. The error shows:
> 
> ```
>   1) Google Cloud Spanner API samples write data with array types and read
>      Failure/Error:
>        write_read_bool_array project_id: @project_id,
>                              instance_id: @instance.instance_id,
>                              database_id: database.database_id
> 
>      ArgumentError:
>        wrong number of arguments (given 1, expected 2)
>      # ./spanner_samples.rb:1506:in `write_read_bool_array'
>      # ./spec/spanner_samples_spec.rb:1459:in `block (3 levels) in <top (required)>'
>      # ./spec/spanner_samples_spec.rb:128:in `capture'
>      # ./spec/spanner_samples_spec.rb:1457:in `block (2 levels) in <top (required)>'
> ```
> 
> I reproduced the error locally but I tried to print out some debugging info:
> 
> ```ruby
>   example "write data with array types and read" do
>     puts "test begin - 1"
>     database = create_boxes_database
>     puts "test end - 1"
> 
>     capture do
>       puts "test begin - 2"
>       write_read_bool_array project_id: @project_id,
>                             instance_id: @instance.instance_id,
>                             database_id: database.database_id
>       puts "test end - 2"
>     end
> 
>     puts "test start - 3"
>     expect(captured_output.split("\n")).to match_array(["true", "false", "true"])
>     puts "test end - 3"
> ```
> 
> It only prints out and then fails:
> 
> ```
> test begin - 1
> test end - 1
> ```

Output will not print to console because  capture redirect console output for test asserts. 
If you want to print output :  `puts captured_output`
Primary key issue will be fixed by : https://github.com/googleapis/google-cloud-ruby/pull/11612

https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/78c099b0bc0447dd4f9f71748c1f66ca17bf4fe6/spanner/spec/spanner_samples_spec.rb#L125-L133

**Comment by hengfengli** [comment]
@jiren Do you have any idea why this acceptance test fails?

**Comment by jiren** [comment]
> @jiren Do you have any idea why this acceptance test fails?

It is failing due to NUMERIC ass a primary key not supported .

**Comment by hengfengli** [comment]
> > @jiren Do you have any idea why this acceptance test fails?
> 
> It is failing due to NUMERIC ass a primary key not supported .

No, I don't think so. The DDL for the table is: 

```
    "CREATE TABLE Boxes (
        BoxId             STRING(36) NOT NULL,
        Heights           ARRAY<INT64>,
        Weights           ARRAY<FLOAT64>,
        ErrorChecks       ARRAY<BOOL>
      ) PRIMARY KEY (BoxId)"
```

Something is wrong with the following code in the `write_read_bool_array`: 

```
  client.insert "Boxes", BoxId: box_id, ErrorChecks: [true, false, true]
```

**Comment by jiren** [comment]
> > > @jiren Do you have any idea why this acceptance test fails?
> > 
> > 
> > It is failing due to NUMERIC ass a primary key not supported .
> 
> No, I don't think so. The DDL for the table is:
> 
> ```
>     "CREATE TABLE Boxes (
>         BoxId             STRING(36) NOT NULL,
>         Heights           ARRAY<INT64>,
>         Weights           ARRAY<FLOAT64>,
>         ErrorChecks       ARRAY<BOOL>
>       ) PRIMARY KEY (BoxId)"
> ```
> 
> Something is wrong with the following code in the `write_read_bool_array`:
> 
> ```
>   client.insert "Boxes", BoxId: box_id, ErrorChecks: [true, false, true]
> ```



> > > @jiren Do you have any idea why this acceptance test fails?
> > 
> > 
> > It is failing due to NUMERIC ass a primary key not supported .
> 
> No, I don't think so. The DDL for the table is:
> 
> ```
>     "CREATE TABLE Boxes (
>         BoxId             STRING(36) NOT NULL,
>         Heights           ARRAY<INT64>,
>         Weights           ARRAY<FLOAT64>,
>         ErrorChecks       ARRAY<BOOL>
>       ) PRIMARY KEY (BoxId)"
> ```
> 
> Something is wrong with the following code in the `write_read_bool_array`:
> 
> ```
>   client.insert "Boxes", BoxId: box_id, ErrorChecks: [true, false, true]
> ```

Ok  got it. Debugging the issue.

**Comment by hengfengli** [comment]
@jiren Sorry, I think I am confused this PR with another PR: https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/803

You're right. The acceptance test fails due to the NUMERIC tests.

**Comment by hengfengli** [comment]
@olavloite Same here.

**Comment by olavloite** [comment]
> @olavloite Same here.

done

**Pull request merged**
