### PR TITLE
make column family cf1 name consistent in the documentation

### PR DESCRIPTION
**Pull request by vasya8844**
Small fix documentation.

[big talbe column description](https://github.com/googleapis/google-cloud-ruby/issues/8407)

closes: #8407

### CODE REVIEW

**Comment by quartzmo** [comment]
@vasya8844 Thanks for this fix. Are you able to sign the CLA? If not, you can close this PR and I will make the changes in a new PR if you want.

**Comment by vasya8844** [comment]
Hi, i've signed

**Comment by quartzmo** [comment]
@vasya8844 I think you might need to reply with this exact phrase: `@googlebot I signed it!`

**Comment by vasya8844** [comment]
@googlebot I signed it!

**Review by quartzmo — APPROVED** [review]
Thank you for this PR!

**Pull request merged**
