### PR TITLE
Bigtable: Hello world example with readme

### PR DESCRIPTION
**Pull request by jiren**
- Readme with Bigtable instance setup instructions
- Hello word example

### CODE REVIEW

**Comment by blowmage** [comment]
Is this good to be merged?

**Comment by jiren** [comment]
@blowmage required review from @sduskis

**Comment by blowmage** [comment]
Any reason why these samples are being added to the client repo and not the shared doc sample repo?

https://github.com/GoogleCloudPlatform/ruby-docs-samples

**Comment by sduskis** [comment]
@blowmage, I'm ok moving the docs there.  I guess different languages have different conventions.

**Comment by blowmage** [comment]
@sduskis What should we do with this PR?

**Comment by jiren** [comment]
@blowmage Closing this pull request and creating against 
https://github.com/GoogleCloudPlatform/ruby-docs-samples

**Pull request closed without merging**
