### PR TITLE
Storage Bucket lock

### PR DESCRIPTION
**Pull request by quartzmo**
Add retention policy and hold fields to Bucket and File.

### CODE REVIEW

**Comment by quartzmo** [comment]
Currently blocked by [failing acceptance tests](https://github.com/quartzmo/google-cloud-ruby/blob/storage-bucket-lock/google-cloud-storage/acceptance/storage/bucket_lock_retention_policy_test.rb#L57-L176) (bug is in GCS):


```sh
1) Failure:
Google::Cloud::Storage::Bucket::lock_retention_policy::storage#test_0002_manages a file with retention_period [/Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-storage/acceptance/storage/bucket_lock_retention_policy_test.rb:88]:
Expected /is subject to bucket's retention policy/ to match "forbidden: Forbidden".

  2) Failure:
Google::Cloud::Storage::Bucket::lock_retention_policy::storage#test_0003_manages a file with default_event_based_hold [/Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-storage/acceptance/storage/bucket_lock_retention_policy_test.rb:129]:
Expected /is under active Event-Based hold/ to match "forbidden: Forbidden".

  3) Failure:
Google::Cloud::Storage::Bucket::lock_retention_policy::storage#test_0004_manages a file with temporary_hold [/Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-storage/acceptance/storage/bucket_lock_retention_policy_test.rb:166]:
Expected /is under active Temporary hold/ to match "forbidden: Forbidden".
```

**Comment by blowmage** [comment]
Do we know when `do not merge` can be removed from this PR?

**Comment by frankyn** [comment]
Expecting to know sometime next week.

**Comment by frankyn** [comment]
You can now merge & release.

**Comment by blowmage** [comment]
@quartzmo Does this branch pass acceptance tests?

**Comment by quartzmo** [comment]
I just ran acceptance tests for my development project and the CI project, and both passed.

**Comment by quartzmo** [comment]
@frankyn Do you want to approve this PR?

**Comment by frankyn** [comment]
Unfortunately I can't. Will need to ask for write permission since the Github Org change.

**Comment by quartzmo** [comment]
@frankyn OK, I'll merge now.

**Comment by quartzmo** [comment]
@frankyn OK to release Monday?

**Pull request merged**
