### PR TITLE
[WIP] chore: release google-cloud-vision@0.35.0

### PR DESCRIPTION
**Pull request by bcoe**
:robot: I have created a release \*beep\* \*boop\* 
---
### Features

* **vision:** Add parent to BatchAnnotate and add PurgeProducts ([97a326d](https://www.github.com/googleapis/google-cloud-ruby/commit/97a326d))
---

This PR was generated with [Release Please](https://github.com/googleapis/release-please).

### CODE REVIEW

**Comment by bcoe** [comment]
this is a work in progress PR, introducing automated release PRs based on conventional commit messages.

**Comment by bcoe** [comment]
@dazuma @quartzmo, had a bit of a discussion in air with @TheRoyalTnetennba's, any thoughts on CHANGELOG template?

The template that this PR is based on has some niceties like:

* automatically linking GitHub names, e.g., `@bcoe`.
* automatically linking PR numbers, e.g., `#10`.
* calling attention to breaking changes in their own section.
* dividing out features into sections.

Here's what the CHANGELOG ends up looking like:

https://github.com/googleapis/nodejs-storage/blob/master/CHANGELOG.md

Personally, I like it, and it means we're not forking from the upstream [open source project](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits/templates).

... I also understand that it looks a little different from the current CHANGELOG template, and this might potentially be a little jarring. If you give me a laundry list of changes you'd like, I could potentially fork the template for you.

**Comment by blowmage** [comment]
Can we use the release process we have already defined in releasetool?

**Comment by blowmage** [comment]
Or does this replace use of releasetool?

**Comment by bcoe** [comment]
@blowmage it replaces and automates the front half of `releasetool`.

* rather than manually running `releasetool`, and editing a CHANGELOG update, `release-please` runs as a service and maintains an [up-to-date release PR](https://github.com/googleapis/nodejs-storage/pull/803).
* the version bump, and content of the CHANGELOG, is based on a more thorough parse of conventional commit messages, and [open source tooling](https://github.com/conventional-changelog/conventional-changelog).
* when the PR is merged, `releasetool` takes over, and the actual gem publication is the same.

**Comment by bcoe** [comment]
@blowmage rather than having to update the CHANGELOG manually, I can make a template that matches this format.

**Comment by blowmage** [comment]
> rather than having to update the CHANGELOG manually, I can make a template that matches this format.

Right, that's why I was asking about using what we've already done in releasetool. We've already customized it to be closer to our preferred format. But even then there are times when we want to edit the changelog manually. I would hope this new process allows for that.

**Comment by quartzmo** [comment]
> But even then there are times when we want to edit the changelog manually. I would hope this new process allows for that.

The new process for manually updating the changelog will be to push a commit to the generated release PR, just like you did today, right?

**Comment by blowmage** [comment]
Gem is [here](https://rubygems.org/gems/google-cloud-vision/versions/0.35.0). Docs are [here](https://googleapis.dev/ruby/google-cloud-vision/v0.35.0/index.html). The release looks like it was successful!

**Comment by bcoe** [comment]
@quartzmo @blowmage the new process will be identical to this, so you can certainly edit immediately before landing; hopefully we can get it close enough to the preferred format that this is done rarely.

**Pull request merged**
