### PR TITLE
Fix link format in OVERVIEW.md

### PR DESCRIPTION
**Pull request by schmijos**

### CODE REVIEW

**Comment by schmijos** [comment]
@googlebot I signed it!

**Comment by blowmage** [comment]
Waiting for @googlebot to verify the CLA is signed before approving.

**Comment by blowmage** [comment]
@schmijos Can you double check the email you signed the CLA with is the same you use for your github/commits?

**Comment by schmijos** [comment]
@blowmage Actually I filled out the form on my company behalf. I got the first email with the link to this fancy signing tool, signed and submitted the form. But I never received the announced confirmation mail. I guess it's easier if you do it yourself.

**Pull request closed without merging**
