### PR TITLE
chore: removing unsupporte samples from repo

### PR DESCRIPTION
**Pull request by munkhuushmgl**
go/cloud-ai-2021-snippet-cleanup

Devsite update: cl/362969424

Additional devsite update to fix snippet bot issues:
cl/363468337 [pending]

all sample browser issues --> I cannot delete single language support from sample browser page for now. Therefore, we have to delete first on github, then regenerate sample browser right after.

### CODE REVIEW

**Comment by dazuma** [comment]
This looks okay, but we need to remove the remaining reference from https://cloud.google.com/vision/product-search/docs/get-list-resources first.

**Comment by dazuma** [comment]
I also don't see the planned "Additional Languages" tab on the pages where samples were removed.

**Comment by munkhuushmgl** [comment]
> I also don't see the planned "Additional Languages" tab on the pages where samples were removed.

That's something in process, I do not have ETA for that.

**Comment by munkhuushmgl** [comment]
> This looks okay, but we need to remove the remaining reference from https://cloud.google.com/vision/product-search/docs/get-list-resources first.

If you are referring to sample browser references, currently, there is no easy way to remove single language from region tag sample browser page.

Sample browser deprecate button only delete region_tag as whole.

Therefore, I have been removing github first, then regenerate sample browser right after PR is merged.

I am aware that it causes temporary 404 on the links on published pages.

**Comment by dazuma** [comment]
I'm not referring to the sample browser references. I'm referring to a specific place in one of the how-to guide pages that still has a Ruby sample tab: https://cloud.google.com/vision/product-search/docs/get-list-resources#getting_a_single_product

**Comment by munkhuushmgl** [comment]
> I'm not referring to the sample browser references. I'm referring to a specific place in one of the how-to guide pages that still has a Ruby sample tab: https://cloud.google.com/vision/product-search/docs/get-list-resources#getting_a_single_product

Sorry about that, I probably missed that one.

**Comment by munkhuushmgl** [comment]
> I'm not referring to the sample browser references. I'm referring to a specific place in one of the how-to guide pages that still has a Ruby sample tab: https://cloud.google.com/vision/product-search/docs/get-list-resources#getting_a_single_product

I created CL for that missing region tag
cl/363742957

**Review by dazuma — APPROVED** [review]

**Comment by munkhuushmgl** [comment]
@dazuma Can u merge it for me?

I do not have write access to this repo

**Pull request merged**
