### PR TITLE
docs(samples): Add Vertex AI Text Prompt Sample

### PR DESCRIPTION
**Pull request by holtskinner**
- Based on this Java sample: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/HEAD/aiplatform/src/main/java/aiplatform/PredictTextPromptSample.java
  - Belongs in this spot in the docs: https://cloud.google.com/vertex-ai/docs/generative-ai/text/test-text-prompts#test_text_prompts
- Also added Endpoint override to Document AI Client

### CODE REVIEW

**Comment by SandeepTuniki** [comment]
@holtskinner A sample test is failing. Can you take a look?

**Comment by holtskinner** [comment]
@SandeepTuniki The current error is because the Vertex AI API wasn't yet enabled in the test project. I went in and enabled it, could you please add the `kokoro:force-run` tag to this PR to make it re-run the test?

**Comment by holtskinner** [comment]
@SandeepTuniki issue has been fixed and the Vertex AI API was enabled in the test project. Good to re-review

**Review by SandeepTuniki — APPROVED** [review]
LGTM

**Comment by SandeepTuniki** [comment]
sample(ai_platform): Add Vertex AI text prompt sample (#23499)

**Pull request merged**
