### PR TITLE
Update Google::Cloud logging README to latest implementation

### PR DESCRIPTION
**Pull request by csmetcalfe**

### CODE REVIEW

**Comment by csmetcalfe** [comment]
I signed it!

**Comment by blowmage** [comment]
@csmetcalfe Thanks for this. 

@TheRoyalTnetennba Any idea why the CLA check hasn’t been updated?

**Comment by csmetcalfe** [comment]
I signed it a second time!

**Comment by blowmage** [comment]
I'm sorry, I misread the changes over the weekend. This change actually reverts to an earlier implementation. We will continue to support `gcloud = Google::Cloud.new` and `gcloud.logging`, but we are intentional in recommending `Google::Cloud::Logging.new`. We are showing the library-specific constructor in all the documentation, except for the old constructor methods.

I had originally thought that we had the old style in the README, and you were updating to the new style.

**Comment by csmetcalfe** [comment]
Ah makes sense. Thanks for the clarification.

**Comment by csmetcalfe** [comment]
Closing.

**Pull request closed without merging**
