### PR TITLE
feat(google-cloud-storage): support OLM Prefix/Suffix

### PR DESCRIPTION
**Pull request by SandeepTuniki**
Implements #17985

~Tests are not expected to pass until the feature is released~. The feature is released now, so the tests should pass.

### CODE REVIEW

**Comment by shaffeeullah** [comment]
@SandeepTuniki , tests should be passing now. can you please confirm?

**Comment by SandeepTuniki** [comment]
@shaffeeullah There's a bug in my code which needs to be fixed. Let me solve it and get back on this.

**Comment by shaffeeullah** [comment]
@SandeepTuniki this feature has been released and this PR can be merged when it's ready

**Comment by SandeepTuniki** [comment]
The failing acceptance test case is failing for main branch too. It is being tracked at #18342

**Comment by SandeepTuniki** [comment]
The bug is fixed now (cc: @shaffeeullah). This PR is ready for review.

The failing acceptance test case is failing for main branch too. It is being tracked at #18342

**Review by dazuma — APPROVED** [review]
LGTM

**Review by bajajneha27 — APPROVED** [review]
LGTM

**Pull request merged**
