### PR TITLE
feat(spanner): add cmek backup support

### PR DESCRIPTION
**Pull request by hengfengli**

### CODE REVIEW

**Review by skuruppu — APPROVED** [review]

**Review by jiren — CHANGES_REQUESTED** [review]
@hengfengli Please add/update doctest and `@example` block in code file.

**Comment by skuruppu** [comment]
@jiren if you could make the suggested changes and push to this branch, that would be great. @hengfengli will be away for a couple of months so won't be able to complete this work.

**Comment by jiren** [comment]
> @jiren if you could make the suggested changes and push to this branch, that would be great. @hengfengli will be away for a couple of months so won't be able to complete this work.

Ok. In this case I need to create a separate pull request because I will not able to push the code to @hengfengli branch.

**Comment by jiren** [comment]
@skuruppu Created PR https://github.com/googleapis/google-cloud-ruby/pull/8167 with doctest updates and example.

**Comment by skuruppu** [comment]
Closing since @jiren will rebase his PR.

**Pull request closed without merging**
