### PR TITLE
chore(spanner): Update minitest to 5.14

### PR DESCRIPTION
**Pull request by quartzmo**
Use `rubocop-minitest` gem and `bundle exec rubocop --only Minitest/GlobalExpectations -a` to autocorrect minitest warnings for Ruby 2.7.

refs: #4110
refs: #4116

### CODE REVIEW

**Comment by quartzmo** [comment]
I've been trying to get a successful `rake acceptance` run for this gem, but it has been hanging:

```
% b rake acceptance
Run options: --seed 35659

# Running:

.......................................................................................................................................................................Error while cleaning up instances and databases after spanner tests.

4:Deadline Exceeded


```

**Comment by dazuma** [comment]
@quartzmo Does it also hang without the minitest conversion?

**Comment by quartzmo** [comment]
> Does it also hang without the minitest conversion?

Yes, I ran once before making changes and that run did not complete either.

**Comment by quartzmo** [comment]
I checked the log for the most recent linux nightly on Kokoro (8 hours ago), it succeeded there. So I will try again now locally using `master`.

```
***************************************
*** google-cloud-spanner acceptance ***
***************************************

Run options: --seed 2124

# Running:

..........................................................................................................................................................................................................................................................

Finished in 903.844925s, 0.2766 runs/s, 4.2076 assertions/s.

```

**Comment by quartzmo** [comment]
It looks like the problem is exceeding the maximum number of pending backups:

```
Google::Cloud::FailedPreconditionError: 9:Cannot create backup (projects/bustling-kayak-91516/instances/google-cloud-ruby-tests/backups/gcruby-200422-9cab42ca-cancel) for database (projects/bustling-kayak-91516/instances/google-cloud-ruby-tests/databases/gcruby-200422-9cab42ca) because the maximum number of pending backups (1) for the database has been reached. Please retry the operation once the pending backups complete.
```

Trying a test run with a different project.

**Comment by dazuma** [comment]
Hmm. That sounds like a test that's going to flake on us a lot, any time multiple tests overlap or tests otherwise happen too quickly. A database backup seems like a heavyweight operation that shouldn't happen as often as these test will run. I think we should consider disabling it (open a separate issue to do so.)

**Comment by quartzmo** [comment]
> I think we should consider disabling it (open a separate issue to do so.)

I think you're right. I'm currently running the acceptance tests locally using the CI project. They appear to have hung again. When it finally exits I'll post the results here, and if it's the backups again, open the new issue.

**Comment by quartzmo** [comment]
Same errors with the other project:

```
Google::Cloud::FailedPreconditionError: 9:Cannot create backup (projects/bustling-kayak-91516/instances/google-cloud-ruby-tests/backups/gcruby-200422-9cab42ca-cancel) for database (projects/bustling-kayak-91516/instances/google-cloud-ruby-tests/databases/gcruby-200422-9cab42ca) because the maximum number of pending backups (1) for the database has been reached. Please retry the operation once the pending backups complete.
```

**Pull request merged**
