### PR TITLE
docs(firestore): remove dual-homed region tags

### PR DESCRIPTION
**Pull request by Strykrol**
Remove unnecessary+outdated region tags now that new ones have proliferated in docs.

### CODE REVIEW

**Comment by Strykrol** [comment]
cl/376017137 and cl/376022748 handle region tag violations.

**Review by crwilcox — APPROVED** [review]
🙌  ty.

**Comment by dazuma** [comment]
Snippet-bot is still flagging those violations when I rerun it. The CLs in question look like they're modifying shared files, so it's possible someone needs to manually trigger a rebuild of the relevant docs pages.

**Comment by Strykrol** [comment]
> Snippet-bot is still flagging those violations when I rerun it. The CLs in question look like they're modifying shared files, so it's possible someone needs to manually trigger a rebuild of the relevant docs pages.

Could you re-run the check tomorrow? I'm not certain if I personally can (should*) manually publish+ and build assets, but devsite should auto-publish from head every few hours anyways.

**Comment by Strykrol** [comment]
@dazuma Could you refresh the snippet bot comment? I'm not able to do so, but I've got those pages re-built manually, and I'm hoping we're good to go now.

**Comment by tmatsuo** [comment]
@Skyrol I re-run the check, and snippet-bot thinks it's OK now.
(but there's a bug that snippet-bot doesn't override the failing status)

You can ignore the snippet-bot check. Thanks.

**Review by dazuma — APPROVED** [review]

**Pull request merged**
