### PR TITLE
Fix label_detection helper smoke test

### PR DESCRIPTION
**Pull request by blowmage**
This change changes the helper tests so they pass and the build will succeed.

### CODE REVIEW

**Comment by quartzmo** [comment]
What do you think about relaxing the assertion, maybe changing to `refute labels.empty?` or something like that?

**Comment by blowmage** [comment]
@TheRoyalTnetennba ^ What do you think about Chris' question?

**Comment by TheRoyalTnetennba** [comment]
`refute labels.empty?` SGTM

**Comment by blowmage** [comment]
Okay, updated to use `refute_empty labels`. PTAL.

**Pull request merged**
