### PR TITLE
Update pubsub namespace to standardize on Google::Cloud::PubSub

### PR DESCRIPTION
**Pull request by dazuma**
Updates and consolidates namespaces for the Pubsub library. Specifically:
* Moves proto data type classes from `Google::Pubsub::V1` to `Google::Cloud::PubSub::V1`
* Moves generated gapic classes from `Google::Cloud::Pubsub` to `Google::Cloud::PubSub`.
* Preserves the `google/cloud/pubsub` file path (as opposed to moving to `google/cloud/pubsub`.
* Aliases were created so `Google::Pubsub` and `Google::Cloud::Pubsub` will continue to work.
* Updated all manually written classes, tests, documentation accordingly.

Note that this essentially encompasses the following steps:
* Assume the upstream configs (both proto and gapic) have been updated with the new namespace.
* Updated the synth file to:
  * Rename the `google/cloud/pub_sub` directory to `google/cloud/pubsub` because gapic is trying to use the Ruby convention for the new name whereas we want to preserve the existing directory structure.
  * Go through generated require statements and fix them with the above change.
  * Update the gapic generated code and docs so they use the new namespace for proto classes (patch for https://github.com/googleapis/gapic-generator/issues/2525)
  * Update the generated proto classes to ensure the modules are defined correctly and an alias is left for the old name (patch for https://github.com/protocolbuffers/protobuf/issues/5584)* Re-ran synth to update the generated files
* Reran synth to update the generated files.
* Did a global search and replace for affected handwritten code, tests, and documentation.

Caveats:
* There is a proto class (data type) called `PubsubMessage`. This was moved namespaces along with the other classes, but its name itself was not changed (e.g. not to PubSubMessage).
* The proto data types are still located in the `google/pubsub/v1/*.rb` files. Those _could_ be moved into `google/cloud/pubsub/v1` with the application of a bit more synth magic, but I don't think it's necessary to do so and risk breaking any users who happen to be trying to require those files directly.

This supersedes #2796 and #2782

### CODE REVIEW

**Comment by blowmage** [comment]
It would be interesting to leave the current code in place, and see if the aliases worked.

I see a mapping for `Google::Pubsub` to `Google::Cloud::PubSub`, but I don't see one for `Google::Cloud::Pubsub` to `Google::Cloud::PubSub`.

**Comment by dazuma** [comment]
The `Google::Cloud::Pubsub` => `Google::Cloud::PubSub` alias is at the bottom of `lib/google/cloud/pubsub.rb`.

**Comment by blowmage** [comment]
Ah, I see it now. I would like to see that `Google::Cloud::Pubsub` to `Google::Cloud::PubSub` alias added to every GAPIC file that comes from the `pub_sub` directory (GAPIC clients and other files), and I think we will want to add it to every veneer file.

What I worry about is someone who does a deep require to add a monkey-patch using the previous namespace. For example, requires only the publisher client file and adds a custom method. It may not be very likely, but that's why I think that alias needs to be on every GAPIC and veneer file.

**Comment by dazuma** [comment]
@blowmage SGTM. Done.

**Pull request merged**
