### PR TITLE
Add project_id to Bigquery::Table#extract and #extract_job

### LINKED ISSUE #2609: BigQuery: Run job in one project that uses resources from another
This is a feature request if it is not supported by the library. See last line for tldr. I am updating a ruby sample to match the [python sample for extracting a table](https://github.com/googleapis/google-cloud-python/blob/cf04f6d15615b09c1de9e584bb3462653f0770f1/bigquery/docs/snippets.py#L1890). The python sample extracts the bigquery-public-data shakespeare table to a GCS bucket. When attempting this in ruby, I ran into a permissions error because of the way the request was structured by the library. The ruby library's [extract_job method](http://googleapis.github.io/google-cloud-ruby/docs/google-cloud-bigquery/v1.9.0/Google/Cloud/Bigquery/Table.html#extract_job-instance_method) is attached to a table instance, so it tries to use the table's project to run the job.

#### Environment details

  - OS: macOS High Sierra
  - Ruby version: 2.4.4
  - Gem name and version: google-cloud-bigquery 1.8.0

#### Steps to reproduce

Run code with bucket_name replaced with an actual bucket:
```ruby
require "google/cloud/bigquery"

bucket_name = "my-bucket"
bigquery = Google::Cloud::Bigquery.new project: "bigquery-public-data"
dataset = bigquery.dataset "samples"
table = dataset.table "shakespeare"
destination_uri = "gs://#{bucket_name}/shakespeare.csv"

extract_job = table.extract_job(destination_uri) do |updater|
  # Location must match that of the source table.
  updater.location = "US"
end
extract_job.wait_until_done!  # Waits for the job to complete

puts "Exported #{table.id} to #{destination_uri}"
```

I get this error on the line where the `extract_job` is defined:
```
Google::Cloud::PermissionDeniedError:
       accessDenied: Access Denied: Project bigquery-public-data: The user <MY-SERVICE-ACCOUNT> does not have bigquery.jobs.create permission in project bigquery-public-data.
```

Is there any way to send an extract job with one project that uses resources in another project?

### PR DESCRIPTION
**Pull request by quartzmo**
[fixes #2609]

/cc @alixhami

### CODE REVIEW

**Comment by alixhami** [comment]
Would this argument be added for other kinds of jobs? I think this issue applies to more than just extract jobs.

I also like the original idea of adding a project as an optional parameter when constructing a dataset (though it will not solve this issue alone). In the other languages, the "client" object is constructed with the project you use to run jobs. It looks weird that in ruby you have to construct a client with the `bigquery-public-data` project for certain operations. @tswast and I noticed this when I wrote a [ruby version](https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/d6f625273f5a67ba3210cf5626197cdc0a763b69/bigquery/snippets/browse_table.rb) (still in PR) of our [python sample](https://github.com/googleapis/google-cloud-python/blob/74dc48d02bb18b69d6d52ff4532763e8bb167de4/bigquery/docs/snippets.py#L1023) for listing table rows. I don't think a client should ever need to be constructed with the `bigquery-public-data` project.

**Comment by quartzmo** [comment]
> Would this argument be added for other kinds of jobs? I think this issue applies to more than just extract jobs.

Yes, I believe it can also be added to `Table#copy` and `Table#copy_job`.

**Comment by quartzmo** [comment]
> In the other languages, the "client" object is constructed with the project you use to run jobs... I don't think a client should ever need to be constructed with the `bigquery-public-data` project.

This library has a hierarchical, OOP-style organization with [`Project`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-bigquery/lib/google/cloud/bigquery/project.rb) (not "Client") at the root of the hierarchy. The creation syntax that makes it appear that a BigQuery client is being created (`bigquery = Google::Cloud::Bigquery.new`) was bolted on later for consistency with other platforms, but this hierarchy remains.

In keeping with the OOP style, operations with the scope of one or two tables are located on the `Table` class. As @tswast [mentioned](https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/370#discussion_r235549151), `tabledata.list` is a free operation, which is fortunate. For the extract and copy operations, a different project may be needed.

I tried the "optional parameter when constructing a dataset" solution, but I found that it leads to errors or surprising behavior for a number of methods in the `Dataset` and `Table` classes.

**Comment by tswast** [comment]
> do you think it would make sense to specify a project for tabledata.list for consistency even though it's a free operation?

Yes, this is because if we provide a way to override the project for tabledata.list, we can avoid having to recreate the client (and repeat doing authorization) to list data in a different project from the one we bill queries to. This is the reason I commented on your sample (https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/370#discussion_r235549151) that it's unfortunate that we can't set the project for tabledata.list.

**Comment by tswast** [comment]
Should we add a `Project.project` method to switch projects but keep the same credentials?

**Comment by blowmage** [comment]
I'm late to this discussion, and I am going to take a slightly different approach. The core problem here is that the Job is created on whatever resource the `#extract` or `#extract_job` method is called on. Specifying `project_id` would solve this, but I think that does not solve the core problem. Please allow me to illustrate.

The original code example is:

```ruby
require "google/cloud/bigquery"

bucket_name = "my-bucket"
bigquery = Google::Cloud::Bigquery.new project: "bigquery-public-data"
dataset = bigquery.dataset "samples"
table = dataset.table "shakespeare"
destination_uri = "gs://#{bucket_name}/shakespeare.csv"

extract_job = table.extract_job(destination_uri) do |updater|
  # Location must match that of the source table.
  updater.location = "US"
end
extract_job.wait_until_done!  # Waits for the job to complete

puts "Exported #{table.id} to #{destination_uri}"
```

The problem here is that the Job is being created on the bigquery-public-data project. What if we could do something like this instead?

```ruby
require "google/cloud/bigquery"

bucket_name = "my-bucket"
bigquery = Google::Cloud::Bigquery.new project: "my-project-id"

shakespeare_table_id = "bigquery-public-data.samples.shakespeare"
destination_uri = "gs://#{bucket_name}/shakespeare.csv"

extract_job = bigquery.extract_job(
  from: shakespeare_table_id,
  to: destination_uri
) do |updater|
  # Location must match that of the source table.
  updater.location = "US"
end
extract_job.wait_until_done!  # Waits for the job to complete

puts "Exported #{shakespeare_table_id} to #{destination_uri}"
```

In this example it seems more obvious to me that the Job is going to be built on the my-project-id project. The `from` argument can be any of the ways we represent a table. Thoughts?

**Comment by quartzmo** [comment]
I was also thinking that versions of `#extract_job` and `#extract` that accept a source table parameter could be added to `Project`, just as we have `Project#query` and `Project#query_job`. I also think this could be done in addition to adding `project_id` to the job operations in `Table`.

**Comment by quartzmo** [comment]
As I wrote above, I tried the "optional parameter when constructing a dataset" solution, but I found that it leads to errors or surprising behavior for a number of methods in the Dataset and Table classes.

**Comment by blowmage** [comment]
> Some thoughts:
> 
> `to:` will need to accept a list of URIs, optionally. Since BigQuery can split across several files when extracting a table.
> 
> To parse the `from:` string, you'll probably want similar logic to Python's `TableReference.from_string` which allows omitting the project if it's the same as the client's default project.

Yes, that is my thinking. The `to` argument would be treated the same as the `extract_url` argument on the existing [`Table#extract_job`](http://googleapis.github.io/google-cloud-ruby/docs/google-cloud-bigquery/latest/Google/Cloud/Bigquery/Table.html#extract_job-instance_method), which allows the value to be a single string or an array of strings.

We also already have code to extract a table from string which allows omitting the project and dataset. It is currently being used in methods like [`Dataset::Access#add_reader_view`](http://googleapis.github.io/google-cloud-ruby/docs/google-cloud-bigquery/latest/Google/Cloud/Bigquery/Dataset/Access.html#add_reader_view-instance_method).

**Comment by quartzmo** [comment]
As long as you're OK with runtime errors on `Dataset` and `Table` operations that are not allowed on the external project, I am happy enough to add `project_id` options to `#dataset` and `#table`.

**Comment by blowmage** [comment]
> As I wrote above, I tried the "optional parameter when constructing a dataset" solution, but I found that it leads to errors or surprising behavior for a number of methods in the Dataset and Table classes.

Correct. I don't know what those issues are yet, but as I stated earlier adding new `extract` and `extract_job` methods that take the table as an argument instead of the table object being the owner of the method call should satisfy this request without also taking the additional step of allowing project to be provided when creating a Dataset object. I think it would make the code example read better, but it can be implemented separately.

**Comment by blowmage** [comment]
> As long as you're OK with runtime errors on `Dataset` and `Table` operations that are not allowed on the external project, I am happy enough to add `project_id` options to `#dataset` and `#table`.

Raising when operations are not allowed on these resource objects is consistent with how Pub/Sub and Storage behave. I think that would be a fair tradeoff, but again, should probably be done in a separate PR.

**Comment by blowmage** [comment]
> Should we add a `Project.project` method to switch projects but keep the same credentials?

I don't think that is necessary if we can pass `project_id` when creating a Dataset object.

**Comment by quartzmo** [comment]
I am OK with adding versions of `#extract`, `#extract_job`, `copy` and `copy_job` to `Project`. Do we also want to continue to add `project_id` to those methods in `Table`?

**Comment by tswast** [comment]
>  Do we also want to continue to add project_id to those methods in Table?

This is less necessary if these methods are added to project. We will use the project methods in the examples on cloud.google.com

**Comment by quartzmo** [comment]
OK, sounds good. I'll close this PR and add versions of `#extract`, `#extract_job`, `#copy` and `#copy_job` to `Project` in a new PR.

**Pull request closed without merging**
