### PR TITLE
Update RELEASING.md

### PR DESCRIPTION
**Pull request by quartzmo**
Add top-level Gemfile to new gem stepset.

See discussion in #2894.

### CODE REVIEW

**Comment by blowmage** [comment]
I'll repeat my comment from #2894: The problem is new gems are being added to the repo but not added to the top-level Gemfile. My biggest concern here is not releasing a new gem, but ensuring new gems are configured properly when they are first added to the repo. Some gems live in the repo for months before their initial release. The problem is new gems in repo without being added to the top-level Gemfile causes the test coverage task to break.

Perhaps we need a different guide, specific to adding new gems to the repo, but before they are released?

**Comment by quartzmo** [comment]
That would seem to belong in .github/CONTRIBUTING.md.

**Comment by blowmage** [comment]
I don't know. Most contributors are making changes to an existing gem, I think instructions for adding a new gem might be too much information to throw on them. I think we should have a separate guide/checklist for adding a new gem, whether it is done by a Googler or an external contributor. We can link to this new guide from CONTRIBUTING if we want.

**Comment by TheRoyalTnetennba** [comment]
I agree with mentioning/linking this in CONTRIBUTING.

**Comment by quartzmo** [comment]
A new guide with a stepset dedicated to adding a new gem sounds good to me. Any objections to merging this PR now?

**Pull request merged**
