### PR TITLE
Release google-cloud 0.56.4

### PR DESCRIPTION
**Pull request by TheRoyalTnetennba**
* Add Cloud Asset
* Add Cloud Redis
* Add Cloud Scheduler

### CODE REVIEW

**Comment by TheRoyalTnetennba** [comment]
> Are there any other gems that need to be added? Like assets?

Are stackdriver and debugger omitted deliberately?

**Comment by blowmage** [comment]
Yes. They have a higher ruby version requirement than the rat of the gems.

**Comment by blowmage** [comment]
Yes, I was just about to suggest changing the version number for that reason.

**Comment by quartzmo** [comment]
This release should be `0.57.0`.

**Pull request merged**
