### PR TITLE
Add ReadOnlyTransaction#query convenience method

### LINKED ISSUE #2854: Different API between Transaction and ReadOnlyTransaction for Datastore
#### Environment details

  - OS: Linux 64-Bit Debian base kernel 4.18.10
  - Ruby version: `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]`
  - Gem name and version: `google-cloud-datastore 1.4.0`

#### Steps to reproduce
When attempting to update some code to use a `read_only_transaction` I encountered the following error:
```
NoMethodError:
  undefined method `query' for #<Google::Cloud::Datastore::ReadOnlyTransaction:0x000055f1c7f9bc80>
```

It appears that this is due to the fact that `ReadOnlyTransaction` does not extend `Dataset` where as `Transaction` does.

Would it be possible to update `ReadOnlyTransaction` to extend `Dataset`?

#### Code example

Old Code
```ruby
  task_list_key = datastore.key "TaskList", "default"
  datastore.transaction do |tx|
    task_list = tx.find task_list_key
    query = tx.query("Task").ancestor(task_list)
    tasks_in_list = tx.run query
  end
```

Attempted new code
```ruby
  task_list_key = datastore.key "TaskList", "default"
  datastore.read_only_transaction do |tx|
    task_list = tx.find task_list_key
    query = tx.query("Task").ancestor(task_list)
    tasks_in_list = tx.run query
  end
```

Working new code
```ruby
  task_list_key = datastore.key "TaskList", "default"
  datastore.read_only_transaction do |tx|
    task_list = tx.find task_list_key
    query = datastore.query("Task").ancestor(task_list)
    tasks_in_list = tx.run query
  end
```

/cc: @frankyn

### PR DESCRIPTION
**Pull request by BenWhitehead**
Fixes #2854

### CODE REVIEW

**Comment by quartzmo** [comment]
@BenWhitehead Thanks, we'll look at this soon!!

**Comment by quartzmo** [comment]
Can you adapt [dataset_test.rb#L984-L998](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-datastore/test/google/cloud/datastore/dataset_test.rb#L984-L998) and add it to test/google/cloud/datastore/read_only_transaction_test.rb`?

**Comment by blowmage** [comment]
Are there other convenience methods besides `query` that folks might want added to `ReadOnlyTransaction`? Perhaps `gql`, `entity`, and `key`?

**Comment by quartzmo** [comment]
I think you can make a strong argument for `key` just based on [the headline example for `ReadOnlyTransaction`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-datastore/lib/google/cloud/datastore/read_only_transaction.rb#L42). If you wanted to make the calls to `key` and `query` inside the block, following the logic of #2854, it would be more natural to call them on `tx`.

**Comment by quartzmo** [comment]
@BenWhitehead What is your opinion on adding the other helper methods,`gql`, `entity`, and `key`?

**Comment by BenWhitehead** [comment]
@blowmage @quartzmo I'll look into it. Though it's sounding a bit more like an actual class hierarchy refactor my be necessary (i.e. split `dataset` into two classes `datasetReadOnly` and `datasetReadWrite`) to avoid several duplicate methods (and tests) and the associated overhead.

**Comment by blowmage** [comment]
I would try extracting these methods to a Module before changing the class hierarchy.

**Comment by quartzmo** [comment]
@BenWhitehead Do you have time to add the other helpers, or should we merge this PR now and follow up with a new issue and PR?

**Comment by BenWhitehead** [comment]
@quartzmo I probably won't have to look into adding the other helpers until sometime next week. I would be okay merging this and then following up at a later time.

**Comment by quartzmo** [comment]
Sounds good. We still need to add a unit test but we can handle that.

**Comment by quartzmo** [comment]
It turns out that this branch currently fails in `rake ci` (`doctest`) with the following error [on Kokoro](https://source.cloud.google.com/results/invocations/6accfca0-909a-4aca-bc5f-d95c9837cfb0/log). I discovered this after pulling the branch to add unit tests. I will fix it now and add the unit tests. @TheRoyalTnetennba I'm not sure that Kokoro ever ran for this PR before I added `force-run` a few minutes ago.

```sh

  1) Error:
Google::Cloud::Datastore::ReadOnlyTransaction#query#test_0001_:
Google::Cloud::Datastore::TransactionError: Transaction failed to commit and rollback.
    /tmpfs/src/github/google-cloud-ruby/google-cloud-datastore/lib/google/cloud/datastore/dataset.rb:609:in `rescue in rescue in read_only_transaction'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-datastore/lib/google/cloud/datastore/dataset.rb:606:in `rescue in read_only_transaction'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-datastore/lib/google/cloud/datastore/dataset.rb:602:in `read_only_transaction'
    /root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/yard-doctest-0.1.16/lib/yard/doctest/example.rb:104:in `context'
    /tmpfs/src/github/google-cloud-ruby/google-cloud-datastore/lib/google/cloud/datastore/read_only_transaction.rb:267
    /root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/yard-doctest-0.1.16/lib/yard/doctest/example.rb:96:in `eval'
    /root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/yard-doctest-0.1.16/lib/yard/doctest/example.rb:96:in `evaluate'
    /root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/yard-doctest-0.1.16/lib/yard/doctest/example.rb:67:in `evaluate_example'
    /root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/yard-doctest-0.1.16/lib/yard/doctest/example.rb:52:in `block (4 levels) in generate'
    /root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/yard-doctest-0.1.16/lib/yard/doctest/example.rb:49:in `each'
    /root/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/yard-doctest-0.1.16/lib/yard/doctest/example.rb:49:in `block (3 levels) in generate'
```

**Comment by TheRoyalTnetennba** [comment]
@quartzmo I think it only automatically runs when the author is in one of the yoshi teams.

**Comment by quartzmo** [comment]
@TheRoyalTnetennba Thanks, I need to remember that.

**Comment by quartzmo** [comment]
@BenWhitehead To expose the root cause of the `doctest` error I locally added a unit test. It turns out that you added the `query` method below `protected`, so it isn't visible. Just goes to show, even with the simplest change tests are always a good idea.

```sh
Google::Cloud::Datastore::ReadOnlyTransaction::mock_datastore#test_0004_query returns a Query instance:
NoMethodError: protected method `query' called for #<Google::Cloud::Datastore::ReadOnlyTransaction:0x00007f8c26a7adc8>
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-datastore/test/google/cloud/datastore/read_only_transaction_test.rb:149:in `block (2 levels) in <top (required)>'
```

**Comment by quartzmo** [comment]
I am working on adding the `key` and `gql` helpers now.

@blowmage I don't think the `entity` helper makes much sense in the context of `ReadOnlyTransaction`.

**Comment by BenWhitehead** [comment]
@quartzmo Thanks a bunch for taking over this. After looking at your diff I think I would be in over my head trying to get all this put together with my limited Ruby knowledge.

Is there anything I need to do to get the `cla/google` status bot to be happy and give a green status?

**Comment by quartzmo** [comment]
@BenWhitehead Nope, the CLA is in "a terminal state, meaning the `cla/google` commit status will not change from this state." At this point we just manually verify that everyone has signed the CLA.

Thanks a ton for bringing this issue to our attention and opening the PR!

**Pull request merged**
