### PR TITLE
Update naming convention for dryrun

### PR DESCRIPTION
**Pull request by blowmage**
* Make this usage of `dryrun` argument consistent with existing usage.
* Add aliases to `QueryJob` and `QueryJob::Updater` with alternative naming.

### CODE REVIEW

**Comment by blowmage** [comment]
cc/ @tswast Thought on this change?

**Comment by tswast** [comment]
LGTM to be consistent with other uses of dryrun. We didn’t release with dry_run yet right?

**Comment by quartzmo** [comment]
@tswast No, we did not release `dry_run` yet. The unmerged release PR is #2710.

**Comment by quartzmo** [comment]
@blowmage I think you missed [this acceptance test usage](https://github.com/googleapis/google-cloud-ruby/blob/f7cb7db1811819afcd31be349a057b71210c2616/google-cloud-bigquery/acceptance/bigquery/bigquery_test.rb#L153). Might be good to do another complete search.

**Comment by blowmage** [comment]
@quartzmo Updated. PTAL.

**Comment by blowmage** [comment]
Right, that is what I stated in the PR description. The method name is `QueryJob#dryrun`, but it is aliased as `QueryJob#dryrun?`, `QueryJob#dry_run`, and `QueryJob#dry_run?`. The method is part of the public API, and not internal, and so are the aliases. Do you not want those aliases?

**Comment by blowmage** [comment]
Oh, I misunderstood your point. I see what you  mean now. I'll change all internal usage to the method, not the alias.

**Comment by quartzmo** [comment]
Last commit looks good, but I think you missed the usage I linked: https://github.com/googleapis/google-cloud-ruby/blob/f7d3279d2160793ea7b28eb7bc2b5736c42b108c/google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb#L576

**Comment by blowmage** [comment]
K, updated again.

**Pull request merged**
